%% Регрессия: все формы узлов, все виды стрелок, цепочки, перенос подписей, ";" и комментарии.
graph RL
    Rect[Прямоугольник] --> Round(Скруглённый) --> Circle((Круг))
    Circle --- Diamond{Ромб?}
    Diamond -.-> Sub[[Подпрограмма]]
    Diamond ==> Cyl[(База)]
    Sub <--> Hex{{Шестиугольник}}
    Cyl -. пунктир .-> Para[/Вход/]
    Para == жирная ==> ParaAlt[\Выход\]
    ParaAlt -->|с подписью| Long[Очень длинная подпись узла, которая переносится на несколько строк<br>и явный перенос]
    Quoted["Текст в кавычках --> не стрелка"] --> Rect; Bare --> Quoted %% комментарий в конце строки
    Rect -- да --> Diamond -- "нет" --> Bare
